apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-client-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-client-app
  template:
    metadata:
      labels:
        app: todo-client-app
    spec:
      containers:
      - image: zot.lan:5000/todo-app-client:latest
        name: todo-app-client
        imagePullPolicy: IfNotPresent